### ISSUE TITLE
I am not based!!!!!!!!! >:()((

### ISSUE THREAD

**Issue by Potat0SSack** [ImLazyForName/beckmen-3#2]
![Без названия (11)](https://user-images.githubusercontent.com/96910014/147855889-d620ee7c-99bf-4f5c-b49d-ad67f7d2e78f.jpg)
![Без названия (10)](https://user-images.githubusercontent.com/96910014/147855890-33132a26-9971-4682-a52c-a70b46a6f7b3.jpg)
![depositphotos_207253996-stock-illustration-mad-angry-emoticon](https://user-images.githubusercontent.com/96910014/147855891-811e1cd9-1e53-4983-8764-d1c18dacbb69.jpg)
![headshot-portrait-funny-young-asian-man-angry-stressed-furious-expression-isolated-grey-asian-man-mad-angry-stressed-106822535](https://user-images.githubusercontent.com/96910014/147855892-83609ec1-fcfd-41bb-9730-c95d8fab8e80.jpg)
**AND I WILL NOT CRY ABOUT IT!!!!!!!!!**
**>:(((((((((((((**

**Comment by Hawkow** [comment]
cry about it

**Comment by ImLazyForName** [comment]
guys stop pls

**Comment by Potat0SSack** [comment]
**NOOOOOOO!!!**
**_I WILL NOT >:((((_**
