### ISSUE TITLE
STOP POSTING ABOUT ISSUES

### ISSUE THREAD

**Issue by Hawkow** [ImLazyForName/beckmen-3#3]
IM TIRED OF SEEING IT, 
MY FRIENDS ON TIKTOK SEND ME ISSUES, ON DISCORD ITS FUCKING ISSUES
I WAS IN A SERVER
RIGHT
AND ALL OF THE CHANNELS WERE JUST ISSUES STUFF
I SHOWED MY CHAMPION UNDERWEAR TO MY GIRLFRIEND AND THE LOGO I FLIPPED IT AND I SAID "HEY BABE, NO BIG GILBERT"
HAHA DING DING DING DING DING DING DING, DING DING DING
I FUCKING LOOK AT A TRASH CAN I SAY, THATS A BIT ISSUE, I LOOK AT MY PENIS I THINK OF BIG GILBER T AND I GO PENIS MORE LIKE ISSUE AAAAAAAAAAAAAAAAAAAAAAA

**Comment by ImLazyForName** [comment]
based

**Comment by Potat0SSack** [comment]
![Desktop Screenshot 2022 01 01 - 20 07 42 18](https://user-images.githubusercontent.com/96910014/147856016-aec60176-d692-4278-a00a-0ffac771a6ef.png)
